apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dp014-cicd
    app.kubernetes.io/instance: dp014-cicd-instance
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: dp014-cicd-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dp014-cicd
  template:
    metadata:
      labels:
        app: dp014-cicd
    spec:
      containers:
        - image: 325583868777.dkr.ecr.ca-central-1.amazonaws.com/dp014-repository:latest
          imagePullPolicy: Always
          name: dp014-cicd
          ports:
            - containerPort: 3000
