apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dp014-cicd
    app.kubernetes.io/instance: dp014-cicd-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: dp014-cicd
spec:
  selector:
    app: dp014-cicd
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 3000
